apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-statestore
  namespace: dapr
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6378
    - name: redisPassword
      value: ""